// IdentityTest.kt
// CarrierPony Android
//
// Two groups: the identity record codec (the JSON inside the Keystore-sealed
// blob), and the baked-in DevIdentity pair. The DevIdentity tests double as a
// GnuPG interop proof: Alice and Bob were generated by GnuPG 2.4.4, so a full
// sign-encrypt-decrypt-verify round trip through the core against these keys
// shows the core handles externally produced key material, not just its own.

package com.carrierpony.app

import com.carrierpony.app.crypto.Fingerprint
import com.carrierpony.app.crypto.PonyCryptoEngine
import com.carrierpony.app.crypto.PublicKey
import com.carrierpony.app.identity.DevIdentity
import com.carrierpony.app.identity.Identity
import com.carrierpony.app.identity.IdentityRecord
import com.carrierpony.core.CPKeyInfo
import com.carrierpony.core.CPMessenger
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class IdentityTest {

    private fun sampleIdentity(protected: Boolean = false) = Identity(
        fingerprint = Fingerprint.from("08108C383A81C409F3E28757397AC5A52B6C5A8D")!!,
        secretKey = byteArrayOf(1, 2, 3, 4, 5, 0, -1, 127),
        armoredPublicKey = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nAAAA\n-----END PGP PUBLIC KEY BLOCK-----\n",
        protected = protected
    )

    // ── Record codec ───────────────────────────────────────────────────

    @Test
    fun recordRoundTrips() {
        val original = sampleIdentity()
        val decoded = IdentityRecord.decode(IdentityRecord.encode(original))
        assertNotNull(decoded)
        assertEquals(original.fingerprint, decoded!!.fingerprint)
        assertArrayEquals(original.secretKey, decoded.secretKey)
        assertEquals(original.armoredPublicKey, decoded.armoredPublicKey)
        assertFalse(decoded.protected)
    }

    @Test
    fun recordRoundTripsProtectedFlag() {
        val decoded = IdentityRecord.decode(IdentityRecord.encode(sampleIdentity(protected = true)))
        assertTrue(decoded!!.protected)
    }

    @Test
    fun recordWithoutProtectedFlagReadsAsFalse() {
        // An older writer's record (iOS stores protected as optional too).
        val json = """{"fingerprint":"08108C383A81C409F3E28757397AC5A52B6C5A8D","secretKeyB64":"AQIDBA==","armoredPublicKey":"x"}"""
        val decoded = IdentityRecord.decode(json)
        assertNotNull(decoded)
        assertFalse(decoded!!.protected)
    }

    @Test
    fun recordRejectsMalformedInput() {
        assertNull(IdentityRecord.decode("not json"))
        assertNull(IdentityRecord.decode("{}"))
        assertNull(IdentityRecord.decode(
            """{"fingerprint":"TOO-SHORT","secretKeyB64":"AQID","armoredPublicKey":"x"}"""))
        assertNull(IdentityRecord.decode(
            """{"fingerprint":"08108C383A81C409F3E28757397AC5A52B6C5A8D","secretKeyB64":"!!!","armoredPublicKey":"x"}"""))
    }

    // ── DevIdentity: baked keys are intact ─────────────────────────────

    @Test
    fun devIdentitiesParse() {
        assertNotNull(DevIdentity.alice)
        assertNotNull(DevIdentity.bob)
        assertEquals("B671D9A8B401BB207C264787A18FB667413300FD", DevIdentity.alice!!.fingerprint.hex)
        assertEquals("61D27B04E1E90899E8D162824891888765D64C51", DevIdentity.bob!!.fingerprint.hex)
    }

    @Test
    fun devFingerprintsRecomputeFromKeyMaterial() {
        for (identity in listOf(DevIdentity.alice!!, DevIdentity.bob!!)) {
            assertEquals(identity.fingerprint.hex, CPKeyInfo.primaryFingerprint(identity.armoredPublicKey))
            assertEquals(identity.fingerprint.hex, CPKeyInfo.primaryFingerprint(identity.secretKey))
            assertEquals(4, CPKeyInfo.keyVersion(identity.secretKey))
        }
    }

    // ── DevIdentity: GnuPG interop through the core ────────────────────

    private fun engine(own: Identity, peer: Identity) = PonyCryptoEngine(
        fingerprint = own.fingerprint,
        secretKey = own.secretKey,
        armored = own.armoredPublicKey,
        publicKeyResolver = { fpr ->
            if (fpr == peer.fingerprint) PublicKey(peer.fingerprint, peer.armoredPublicKey) else null
        }
    )

    @Test
    fun gnupgKeysRoundTripThroughCore() {
        val alice = DevIdentity.alice!!
        val bob = DevIdentity.bob!!
        val aliceEngine = engine(alice, bob)
        val bobEngine = engine(bob, alice)

        val plaintext = "GnuPG 2.4.4 keys, CarrierPonyCore envelope".toByteArray()
        val envelope = aliceEngine.signAndEncrypt(plaintext, PublicKey(bob.fingerprint, bob.armoredPublicKey))
        val verified = bobEngine.decryptAndVerify(envelope)

        assertEquals(alice.fingerprint, verified.sender)
        assertArrayEquals(plaintext, verified.plaintext)
    }

    @Test
    fun gnupgKeySignsRelayChallenge() {
        val alice = DevIdentity.alice!!
        val armored = CPMessenger.detachedSignature("challenge-nonce".toByteArray(), alice.secretKey)
        assertTrue(armored.contains("-----BEGIN PGP SIGNATURE-----"))
    }
}
